<template>
  <div class="loadingio-spinner-rolling-v9dstz357x">
    <div class="ldio-841d25wka6n">
      <div></div>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import "~/scss/_variables";

  /* generated by https://loading.io/ */
@keyframes ldio-841d25wka6n {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-841d25wka6n div {
  position: absolute;
  width: 60px;
  height: 60px;
  border: 10px solid $color-primary;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-841d25wka6n div {
  animation: ldio-841d25wka6n 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-v9dstz357x {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-841d25wka6n {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-841d25wka6n div { box-sizing: content-box; }
</style>
